services:
  web:
    container_name: web
    build:  # Construire l'image à partir du Dockerfile
      context: .  # Chemin vers le répertoire contenant le Dockerfile
      dockerfile: Dockerfile  # (Facultatif) Nom du fichier Dockerfile si différent
    depends_on :
      - db
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    environment:
      SECRET_KEY: foo
      DJANGO_ALLOWED_HOSTS: 172.20.10.2 127.0.0.1 localhost
      CSRF_TRUSTED_ORIGINS: http://localhost:8080
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: hello_django
      SQL_USER: hello_django
      SQL_PASSWORD: hello_django
      SQL_HOST: db
      SQL_PORT: 5432

  
  db:
    container_name: db
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      DATABASE: postgres
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
      POSTGRES_DB: hello_django


  nginx:
    container_name: nginx
    image: nginx:1.27.1
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on :
      - web

volumes:
  postgres_data:
  static_volume: