# Generated by Django 3.2.19 on 2024-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('entreprise', models.CharField(max_length=50)),
                ('nombreVisiteur', models.IntegerField()),
            ],
        ),
    ]
