# Generated by Django 5.1 on 2024-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rdv_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='time',
        ),
        migrations.AlterField(
            model_name='rdv',
            name='dateTime',
            field=models.DateTimeField(default='2024-09-06 12:12:12+02:00'),
            preserve_default=False,
        ),
    ]
